version: '3.7'

services:
  samba:
    image: dperson/samba
    ports:
      - "139:139"
      - "445:445"
    command: "-u '${SAMBA_USER};${SAMBA_PASS}' -s 'shared;/data;yes;no;yes;all;none'"
    volumes:
      - ./samba-data:/data
    environment:
      SAMBA_USER: ${SAMBA_USER}
      SAMBA_PASS: ${SAMBA_PASS}
    networks:
      - default
